name: Build and Push Container to GCR

on:
  push:
    branches: ['master', 'develop', '*']

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT_ID}}

      - name: Build Docker image
        run: |-
          docker build -t eu.gcr.io/${{secrets.GKE_PROJECT_ID}}/scrapper-api:latest .
          docker build -t eu.gcr.io/${{secrets.GKE_PROJECT_ID}}/scrapper-api:${{ github.sha }} .

      - name: Push Docker image to Google Container Registry
        run: |-
          gcloud --quiet auth configure-docker --project ${{secrets.GKE_PROJECT_ID}}
          docker push eu.gcr.io/${{secrets.GKE_PROJECT_ID}}/scrapper-api:latest
          docker push eu.gcr.io/${{secrets.GKE_PROJECT_ID}}/scrapper-api:${{ github.sha }}
